name:  pull request check

on: pull_request

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          cache: "gradle"
      - name: Run unit test
        run: ./gradlew testDebugUnitTest mergeAndroidReports --continue
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/build/test-results/*/TEST-*.xml'
